const env = require("./env");

module.exports = {
  PORT: env.PORT,
  LOG_LEVEL: env.LOG_LEVEL,
  CONNECTION_STRING: env.CONNECTION_STRING,

  JWT: {
    SECRET: env.JWT_SECRET,
    EXPIRE_TIME: env.TOKEN_EXPIRE_TIME,
  },

  FILE_UPLOAD_PATH: env.FILE_UPLOAD_PATH,
  DEFAULT_LANG: env.DEFAULT_LANG,
  ALLOWED_ORIGINS: env.ALLOWED_ORIGINS,
};
